name: Build Arduino Project

on:
  push:
    branches:
      - main
      - development
  pull_request:
    branches:
      - main
      - development
  # Allows you to run this workflow manually from the Actions tab for every branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set execute permissions for shell scripts
      run: chmod +x ./.ci_scripts/*.sh

    - name: Check commit message format
      run: ./.ci_scripts/check-commit-message.sh

    - name: Check missing keywords and keywords format
      run: ./.ci_scripts/check-missing-keywords.sh

    - name: Download astyle
      run: sudo apt-get install -y astyle

    - name: Check wellformed code style with astyle app
      id: check_astyle
      run: ./.ci_scripts/check-astyle-code.sh
      continue-on-error: true

    - name: Upload astyle restyling.patch file if exists
      #if: steps.check_astyle.outputs.result != '0'
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: restyling.patch
        path: restyling.patch

    - name: Throw Error and end job execution
      #if: steps.check_astyle.outputs.result != '0'
      if: failure()
      run: |
        echo "Code style is not wellformed. End job execution with error."
        return 1

    - name: Set up Arduino CLI
      uses: arduino/setup-arduino-cli@master

    - name: Install dependencies
      run: |
        arduino-cli core update-index
        arduino-cli core install arduino:avr
        arduino-cli lib install "Firmata"
        #arduino-cli lib install "Wire"
        #arduino-cli lib install "SPI"
        arduino-cli lib install "Servo"

    - name: Compile sketch
      run: |
        arduino-cli compile --fqbn arduino:avr:uno Projects/Arduino/Blink/Blink.ino
